name: Daily update

on:
  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: git pull
    - uses: actions/setup-go@v1
      name: "setup go"
      with:
        go-version: '1.13.4'
    - name: "install raid-codex-cli"
      run: |
        go get github.com/raid-codex/tools/cmd/raid-codex-cli
        go install github.com/raid-codex/tools/cmd/raid-codex-cli
    - name: "hellhades"
      run: |
        go env
        export PATH="/home/runner/go/bin:$PATH"
        bash ./scripts/hellhades-tier-list.sh
    - name: "refresh"
      run: |
        export PATH="/home/runner/go/bin:$PATH"
        export DIRECTORY=`pwd`
        make sanitize_champions
        make rebuild_index_champions
    - name: "ayumilove"
      run: |
        export PATH="/home/runner/go/bin:$PATH"
        bash ./scripts/ayumilove-tier-list.sh
    - name: "content creator videos"
      run: |
        git clone https://github.com/raid-codex/content-creators.git
        export DATA_DIRECTORY=`pwd`
        export CONTENT_CREATOR_DIRECTORY=`pwd`/content-creators
        python3 scripts/add-content-creator-videos.py
        rm -rf content-creators
    - name: "refresh"
      run: |
        export PATH="/home/runner/go/bin:$PATH"
        export DIRECTORY=`pwd`
        make sanitize_fusions
        make rebuild_index_fusions
        make sanitize_champions
        make rebuild_index_champions
    - name: "commit changes"
      uses: peter-evans/create-pull-request@v3.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: updated ratings & videos from sources"
        author: Geoffrey Bauduin <geoffreybauduin@users.noreply.github.com>

        title: 'Updated ratings & videos from sources'
        base: master
        body: |
          Automatically generated
        assignees: geoffreybauduin
        reviewers: geoffreybauduin
        
